version: 2.1

orbs:
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-app:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install
          command: pip install -i https://test.pypi.org/simple/ -r requirements.txt
      - run:
          name: Run tests
          command: python -m pytest
    
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-test-deploy:
    jobs:
      - build-app:
          context: ai-eval-examples